name: Rust
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL2
      run: |
        sudo apt-get update -y
        sudo apt-get install libsdl2-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build Release
      run: cargo build --release --verbose
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      if: ${{ github.event_name == 'push' }}
      with:
        name: byte-pusher-emu
        path: target/release/byte-pusher-emu
        if-no-files-found: error
        overwrite: false
